# Generated by Django 4.2.11 on 2025-01-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
