# Generated by Django 4.2.11 on 2025-01-21 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_income_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Expenses',
        ),
    ]
